#!/bin/bash

if [ -z $1 ]; then
	echo "usage: $0 [device_name]"
	exit 1
fi

DEVICE=$1
OUTPUT=output/${DEVICE}.gld

cat >$OUTPUT << ENDHEADER
/************************************************
 Linker script for $DEVICE

 Generated by the Signal 11 Software
 PIC24F Linker Script Generator
 
 http://github.com/signal11/pic_linker_script

 This script may be used by anyone for any
 purpose and may be redistributed freely.
************************************************/
ENDHEADER


cat ${DEVICE}_mem.txt >> $OUTPUT
echo "" >> $OUTPUT

cat pic24f_mem.txt >> $OUTPUT
echo "" >> $OUTPUT

echo "" >> $OUTPUT
echo "#define HANDLER(X) LONG(DEFINED(__##X)? ABSOLUTE(__##X): ABSOLUTE(__DefaultInterrupt));" >> $OUTPUT
echo "" >> $OUTPUT

echo "" >> $OUTPUT
echo "#define ALTHANDLER(X) LONG(DEFINED(__Alt##X)? ABSOLUTE(__Alt##X): DEFINED(__##X) ? ABSOLUTE(__##X) : ABSOLUTE(__DefaultInterrupt));"  >> $OUTPUT
echo "" >> $OUTPUT


echo "SECTIONS {" >> $OUTPUT

cat pic24f_reset.txt  >> $OUTPUT

echo "" >> $OUTPUT

cat pic24f_icd.txt >> $OUTPUT

echo "" >> $OUTPUT

cat pic24f_debug.txt >> $OUTPUT

echo "" >> $OUTPUT

cat pic24f_configs.txt >> $OUTPUT

echo "" >> $OUTPUT

echo -e "\t.intvec IVT_BASE : {" >> $OUTPUT

cat pic24f_interrupts.txt | while read INTERRUPT IMPLEMENTED
do
	if [ $INTERRUPT ]; then
		echo -e  "\t\tHANDLER($INTERRUPT)" >> $OUTPUT
	fi

done

echo -e "\t} >ivt" >> $OUTPUT

echo "" >> $OUTPUT
echo "" >> $OUTPUT

echo -e "\t.altintvec ALT_IVT_BASE : {" >> $OUTPUT

cat pic24f_interrupts.txt | while read INTERRUPT IMPLEMENTED
do
	if [ $INTERRUPT ]; then
		echo -e  "\t\tALTHANDLER($INTERRUPT)" >> $OUTPUT
	fi

done

echo -e "\t} >aivt" >> $OUTPUT



echo "}" >> $OUTPUT # SECTIONS

echo "" >> $OUTPUT

cat ${DEVICE}_regs.txt | while read REG ADDR
do

	if [ $REG ]; then
		echo -e "$REG = 0x$ADDR;" >> $OUTPUT
		echo -e "_$REG = 0x$ADDR;" >> $OUTPUT
		echo -e "_${REG}bits = 0x$ADDR;" >> $OUTPUT
	fi
done



echo "" >> $OUTPUT

